name: ps-printer-app
min-version: 2.5
element-path: elements

(@):
  - include/aliases.yml

options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
      - aarch64
      - x86_64

variables:
  abi: gnu
  gcc-triplet: "%{arch}-linux-%{abi}"
  lib: "lib/%{gcc-triplet}"
  libdir: "%{prefix}/%{lib}"
  (?):
    - arch == "x86_64":
        go-arch: "amd64"
    - arch == "aarch64":
        go-arch: "arm64"

sandbox:
  build-arch: "%{arch}"

artifacts:
  - url: https://gbm.gnome.org:11003
  - url: https://cache.projectbluefin.io:11001

source-caches:
  - url: https://gbm.gnome.org:11003
  - url: https://cache.projectbluefin.io:11001

junctions:
  duplicates:
    buildstream-plugins-community:
      - plugins/buildstream-plugins-community.bst
      - fsdk-containers.bst:plugins/buildstream-plugins-community.bst

plugins:
  - origin: junction
    junction: plugins/buildstream-plugins-community.bst
    sources:
      - git_repo

sources:
  git_repo:
    config:
      ref-format: git-describe
